package com.care.voice.brain.reminder

enum class ReminderFailureCode {
    EXACT_ALARM_PERMISSION_REQUIRED,
    ALARM_SCHEDULE_FAILED,
    NOTIFICATION_DENIED,
    NOTIFICATION_FAILED,
    MISSED_AFTER_REBOOT,
    MISSED_AFTER_DEADLINE,
    STALE_SCHEDULING,
    SNOOZE_SCHEDULE_FAILED,
    RESCHEDULE_FAILED,
    ROOM_UPDATE_FAILED,
    INVALID_STATUS_TRANSITION,
    UNKNOWN
}
